# networks:
#   default:
#     name: zkevm
services:
  zkevm-state-db:
    container_name: zkevm-state-db
    image: postgres:15
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    ports:
      - 5432:5432
    volumes:
      - ./config/scripts/init_prover_db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=aggregator_user
      - POSTGRES_PASSWORD=aggregator_password
      - POSTGRES_DB=aggregator_db
    command:
      - "postgres"
      - "-N"
      - "500"

  zkevm-pool-db:
    container_name: zkevm-pool-db
    restart: unless-stopped
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=pool_user
      - POSTGRES_PASSWORD=pool_password
      - POSTGRES_DB=pool_db
    command:
      - "postgres"
      - "-N"
      - "500"

  zkevm-prover:
    network_mode: host
    container_name: zkevm-prover
    restart: unless-stopped
    image: hermeznetwork/zkevm-prover:v7.0.4-fork.11
    ports:
      - 50061:50061 # MT
      - 50071:50071 # Executor
    volumes:
      - ./config/prover.config.json:/usr/src/app/config.json
    command: >
      zkProver -c /usr/src/app/config.json

  cdk-erigon:
    network_mode: host
    user: root
    container_name: cdk-erigon
    image: hermeznetwork/cdk-erigon:v2.0.0
    restart: always 
    ports:
      - 9092:9092
      - 6900:6900
      - 8123:8123
    volumes:
      - ./config/${CDK_ENVIRONMENT}/cdk-erigon.config.yaml:/etc/cdk-erigon/config.yaml
      - ./erigon-datadir/${CDK_ENVIRONMENT}:/home/erigon/erigon/.local/share/erigon
    # command: ["--config", "/etc/cdk-erigon/config.yaml"]
    entrypoint: /bin/sh
    command:
      - "-c"
      - "chmod -R 777 /home/erigon/erigon/ && CDK_ERIGON_SEQUENCER=1 cdk-erigon --config /etc/cdk-erigon/config.yaml"
  
  cdk-erigon-validium:
    network_mode: host
    user: root
    container_name: cdk-erigon-validium
    image: hermeznetwork/cdk-erigon:v2.60.0-beta8
    restart: always 
    ports:
      - 9092:9092
      - 6900:6900
      - 8123:8123
    volumes:
      - ./config/${CDK_ENVIRONMENT}/cdk-erigon.config.yaml:/etc/cdk-erigon/config.yaml
      - ./config/${CDK_ENVIRONMENT}/dynamic-network-allocs.json:/etc/cdk-erigon/dynamic-network-allocs.json
      - ./config/${CDK_ENVIRONMENT}/dynamic-network-chainspec.json:/etc/cdk-erigon/dynamic-network-chainspec.json
      - ./config/${CDK_ENVIRONMENT}/dynamic-network-conf.json:/etc/cdk-erigon/dynamic-network-conf.json
      - ./erigon-datadir/${CDK_ENVIRONMENT}:/home/erigon/erigon/.local/share/erigon
    entrypoint: /bin/sh
    command:
      - "-c"
      - "chmod -R 777 /home/erigon/erigon/ && CDK_ERIGON_SEQUENCER=1 cdk-erigon --config /etc/cdk-erigon/config.yaml"

  zkevm-pool-manager:
    container_name: zkevm-pool-manager
    restart: unless-stopped
    depends_on:
      zkevm-pool-db:
        condition: service_healthy
    image: hermeznetwork/zkevm-pool-manager:v0.1.1
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    ports:
      - 8124:8124
    volumes:
      - ./config/${CDK_ENVIRONMENT}/poolmanager.config.toml:/app/poolmanager.toml
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-pool-manager run --cfg /app/poolmanager.toml"

  zkevm-shadow-fork:
    network_mode: host
    container_name: zkevm-shadow-fork
    image: ghcr.io/foundry-rs/foundry:latest
    environment:
      - L1_PROVIDER_URL=https://sepolia.infura.io/v3/7c490aa772fa466293ee1ac62761330a
    ports:
      - 8548:8548
    command:
      - "anvil --block-time 12 --port 8548 --fork-url $${L1_PROVIDER_URL} --fork-block-number 6787526"

  zkevm-ssender:
    network_mode: host
    container_name: zkevm-ssender
    image: ghcr.io/0xpolygon/cdk:0.3.2
    restart: always 
    volumes:
      - ./config/${CDK_ENVIRONMENT}/data-cdk-node/ssender-data:/app/data
      - ./config/${CDK_ENVIRONMENT}/genesis.json:/app/genesis.json:ro
      - ./config/${CDK_ENVIRONMENT}/cdk-node-config.toml:/app/config.toml:ro
      - ./config/sequencer.keystore:/app/sequencer.keystore:ro
      #- ./config/aggregator.keystore:/pk/aggregator.keystore:ro
      #- ./config/${CDK_ENVIRONMENT}/data-cdk-node/tmp-ssender:/tmp
    command:
      - "/bin/sh"
      - "-c"
      - "cdk-node run -custom-network-file=/app/genesis.json -cfg=/app/config.toml -components=sequence-sender"

  zkevm-aggregator:
    network_mode: host
    container_name: zkevm-aggregator
    image: ghcr.io/0xpolygon/cdk:0.3.2
    ports:
      - 50081:50081
    volumes:
      #- ./config/${CDK_ENVIRONMENT}/data-cdk-node/aggregator-data:/app/data
      - ./config/${CDK_ENVIRONMENT}/genesis.json:/app/genesis.json:ro
      - ./config/${CDK_ENVIRONMENT}/cdk-node-config.toml:/app/config.toml:ro
      # - ./config/sequencer.keystore:/app/sequencer.keystore:ro
      - ./config/aggregator.keystore:/pk/aggregator.keystore:ro
      - ./config/${CDK_ENVIRONMENT}/data-cdk-node/tmp-aggregator:/tmp
    command:
      - "/bin/sh"
      - "-c"
      - "cdk-node run -custom-network-file=/app/genesis.json -cfg=/app/config.toml -components=aggregator"

  zkevm-dac:
    network_mode: host
    container_name: zkevm-dac
    image: 0xpolygon/cdk-data-availability:0.0.10
    ports:
      - 8444:8444
    volumes:
      - ./config/${CDK_ENVIRONMENT}/dac.config.toml:/app/config.toml:ro
      - ./config/dac.keystore:/pk/dac.keystore:ro
    entrypoint: /bin/sh
    command:
      - "-c"
      - "/app/cdk-data-availability run -cfg=/app/config.toml"
