datadir: ./erigon/.local/share/erigon
chain: hermez-cardona

zkevm.l2-chain-id: 2442
# zkevm.l2-sequencer-rpc-url: https://rpc.cardona.zkevm-rpc.com/
# zkevm.l2-datastreamer-url: datastream.cardona.zkevm-rpc.com:6900
# zkevm.l2-datastreamer-timeout: "0s"

# zkevm.sync-limit: 7351412 # 7351411 is the latest blocknum for batch 128346

zkevm.l1-chain-id: 11155111
zkevm.l1-rpc-url: http://localhost:8545
zkevm.l1-rollup-id: 1
zkevm.l1-first-block: 4789190
zkevm.l1-block-range: 5000
# zkevm.l1-sync-start-block: 4789190 #disable this param to avoid recovery mode

zkevm.address-sequencer: "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"
zkevm.address-zkevm: "0xA13Ddb14437A8F34897131367ad3ca78416d6bCa"
zkevm.address-admin: "0xff6250d0e86a2465b0c1bf8e36409503d6a26963"
zkevm.address-rollup: "0x32d33D5137a7cFFb54c5Bf8371172bcEc5f310ff"
zkevm.address-ger-manager: "0xAd1490c248c5d3CbAE399Fd529b79B42984277DF"

zkevm.executor-strict: false
# zkevm.executor-urls: "${STATELESS_EXECUTOR}"
zkevm.witness-full: false
zkevm.sequencer-block-seal-time: "3s"
zkevm.sequencer-batch-seal-time: "3m"
zkevm.allow-pre-eip155-transactions: true
zkevm.disable-virtual-counters: false

zkevm.default-gas-price: 1
zkevm.max-gas-price: 0
zkevm.gas-price-factor: 0.12

zkevm.rpc-ratelimit: 250

zkevm.data-stream-host: "0.0.0.0"
zkevm.data-stream-port: 6900
zkevm.data-stream-inactivity-timeout: "10m"
zkevm.data-stream-inactivity-check-interval: "1m"
zkevm.data-stream-writeTimeout: "20s"

# zkevm.limbo: ${LIMBO_MODE}


txpool.disable: false
txpool.globalslots: 30000
txpool.globalbasefeeslots: 30000
txpool.globalqueue: 30000
torrent.port: 42070

http: true
private.api.addr: localhost:9092
externalcl: true
http.api: [eth, debug, net, trace, web3, erigon, zkevm, txpool]
http.addr: 0.0.0.0
http.port: 8123
http.vhosts: '*'
http.corsdomain: '*'
ws: true

log.json: true
log.console.verbosity: "debug"

debug.timers: true
